import { Button } from "std-widgets.slint";
import { CenteredPageRoot } from "../components/page-layouts.slint";
import { HeadingLabel } from "../components/heading-label.slint";
import { DescriptionLabel } from "../components/description-label.slint";

export component ConnectionDiscardConfirmationPage inherits CenteredPageRoot {
    in property <string> connection-name;
    callback cancel();
    callback confirm();

    HeadingLabel {
        text: "Discard unsaved changes?";
    }

    DescriptionLabel {
        text: "Your changes to this connection have not been saved.";
    }

    VerticalLayout {
        Button {
            accessible-label: "Continue editing connection " + root.connection-name;
            text: "Continue editing";
            clicked => {
                root.cancel();
            }
        }

        Button {
            accessible-label: "Discard changes to connection " + root.connection-name;
            text: "Discard " + root.connection-name + " changes";
            primary: true;
            clicked => {
                root.confirm();
            }
        }
    }
}
