import { CenteredPageRoot } from "../components/page-layouts.slint";
import { HeadingLabel } from "../components/heading-label.slint";
import { DescriptionLabel } from "../components/description-label.slint";
import { PrimaryActionButton, SecondaryActionButton } from "../components/action-buttons.slint";
import { ActionGroup } from "../components/list-and-action-layouts.slint";

export component ConnectionDiscardConfirmationPage inherits CenteredPageRoot {
    in property <string> connection-name;
    callback cancel();
    callback confirm();

    HeadingLabel {
        text: "Discard Unsaved Changes?";
    }

    DescriptionLabel {
        text: "Your changes to this connection have not been saved.";
    }

    ActionGroup {
        SecondaryActionButton {
            accessible-label: "Continue editing connection " + root.connection-name;
            text: "Keep Editing";
            clicked => {
                root.cancel();
            }
        }

        PrimaryActionButton {
            accessible-label: "Discard changes to connection " + root.connection-name;
            text: "Discard Changes";
            clicked => {
                root.confirm();
            }
        }
    }
}
