import { Colors } from "../colors.slint";
import { Dimensions } from "../dimensions.slint";

component Card inherits Rectangle {
    in property <brush> outline-color;
    in property <brush> fill-color;
    in property <length> baseline-height: 0px;

    background: root.fill-color;
    border-color: root.outline-color;
    border-width: 1px;
    border-radius: Dimensions.card-border-radius;
    min-height: max(root.baseline-height, card-content.preferred-height);
    preferred-height: root.min-height;

    card-content := VerticalLayout {
        padding: Dimensions.card-padding;
        spacing: Dimensions.card-element-spacing;
        @children
    }
}

export component DangerCard inherits Card {
    outline-color: Colors.danger;
    fill-color: Colors.danger-surface;
}

export component SuccessCard inherits Card {
    outline-color: Colors.success;
    fill-color: Colors.success-surface;
}

export component InfoCard inherits Card {
    outline-color: Colors.secondary;
    fill-color: Colors.surface;
}
