import { Colors } from "../colors.slint";
import { Dimensions } from "../dimensions.slint";

export component ErrorLabel inherits Text {
    min-width: 0px;
    max-height: self.preferred-height;
    horizontal-stretch: 1;
    vertical-stretch: 0;
    color: Colors.danger;
    font-size: Dimensions.text-size-description;
    font-weight: 400;
    wrap: word-wrap;
    horizontal-alignment: start;
}
