import { ListView as StandardListView } from "std-widgets.slint";
import { Dimensions } from "../dimensions.slint";

export component ListView inherits StandardListView {
    mouse-drag-pan-enabled: true;
}

export component ListItem inherits VerticalLayout {
    vertical-stretch: 0;
    padding-bottom: Dimensions.element-gap;
    @children
}

export component ActionGroup inherits VerticalLayout {
    spacing: Dimensions.element-gap;
    @children
}

export component ContentGroup inherits VerticalLayout {
    max-height: self.preferred-height;
    vertical-stretch: 0;
    @children
}
