import { ScrollView } from "std-widgets.slint";
import { Dimensions } from "../dimensions.slint";

export component ListView inherits ScrollView {
    accessible-role: list;
    accessible-orientation: Orientation.vertical;

    VerticalLayout {
        width: parent.width;
        alignment: start;
        spacing: Dimensions.element-gap;
        @children
    }
}

export component ListItem inherits VerticalLayout {
    vertical-stretch: 0;
    padding-bottom: Dimensions.element-gap;
    @children
}

export component ActionGroup inherits VerticalLayout {
    spacing: Dimensions.element-gap;
    @children
}
