import { ListView as StandardListView } from "std-widgets.slint";
import { Colors } from "../colors.slint";
import { Dimensions } from "../dimensions.slint";

export component ListView inherits StandardListView {
    mouse-drag-pan-enabled: true;
}

export component ListItem inherits VerticalLayout {
    vertical-stretch: 0;
    padding-bottom: Dimensions.element-gap;
    @children
}

export component ListLoadingIndicator inherits Rectangle {
    in property <string> label;

    accessible-role: progress-indicator;
    accessible-label: root.label;
    vertical-stretch: 1;

    spinner := Path {
        private property <float> radius: 46;
        private property <float> start: mod(animation-tick(), 3s) / 3s;
        private property <float> progress: min(0.9999, max(0.20, abs(sin(360deg * animation-tick() / 1.5s))));

        width: 40px;
        height: 40px;
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
        viewbox-width: 100;
        viewbox-height: 100;
        stroke: Colors.primary;
        stroke-width: 7px;

        MoveTo {
            x: 50 - spinner.radius * sin(-(spinner.start - 0.001) * 360deg);
            y: 50 - spinner.radius * cos(-(spinner.start - 0.001) * 360deg);
        }

        LineTo {
            x: 50 - spinner.radius * sin(-spinner.start * 360deg);
            y: 50 - spinner.radius * cos(-spinner.start * 360deg);
        }

        ArcTo {
            radius-x: spinner.radius;
            radius-y: spinner.radius;
            x: 50 - spinner.radius * sin(-(spinner.start + spinner.progress) * 360deg);
            y: 50 - spinner.radius * cos(-(spinner.start + spinner.progress) * 360deg);
            sweep: spinner.progress > 0;
            large-arc: spinner.progress > 0.5;
        }
    }
}

export component ActionGroup inherits VerticalLayout {
    spacing: Dimensions.element-gap;
    @children
}

export component ContentGroup inherits VerticalLayout {
    max-height: self.preferred-height;
    vertical-stretch: 0;
    @children
}
