import { ScrollView } from "std-widgets.slint";
import { Dimensions } from "../dimensions.slint";

export component PageRoot inherits ScrollView {
    vertical-scrollbar-policy: always-on;
    horizontal-scrollbar-policy: always-off;
}

export component CenteredPageColumn inherits VerticalLayout {
    in property <bool> fill-height;

    HorizontalLayout {
        alignment: center;
        vertical-stretch: root.fill-height ? 1 : 0;

        VerticalLayout {
            preferred-width: Dimensions.welcome-content-max-width;
            max-width: Dimensions.welcome-content-max-width;
            alignment: root.fill-height ? stretch : start;
            horizontal-stretch: 1;
            spacing: Dimensions.content-spacing;
            @children
        }
    }
}

export component CenteredPageRoot inherits PageRoot {
    in property <bool> fill-height;

    CenteredPageColumn {
        width: root.visible-width;
        fill-height: root.fill-height;
        @children
    }
}
