export global Colors {
    in-out property <bool> dark-mode: false;
    out property <brush> app-background: dark-mode ? #000000 : #f7f2e8;
    out property <brush> surface: dark-mode ? #1c1a17 : #fffaf0;
    out property <brush> primary: dark-mode ? #bc31ff : #171512;
    out property <brush> secondary: dark-mode ? #e4bda3 : #454039;
    out property <brush> danger: dark-mode ? #ffb4ab : #7b241c;
    out property <brush> danger-surface: dark-mode ? #5c1715 : #fff4f2;
    out property <brush> success: dark-mode ? #87d89a : #23623a;
    out property <brush> success-surface: dark-mode ? #183d24 : #f2fbf3;
    out property <brush> progress-track: dark-mode ? #8cb9ca : #e2ddd4;
}
