export global Dimensions {
    out property <length> text-size-heading: 32px;
    out property <length> text-size-section-header: 22px;
    out property <length> text-size-description: 16px;
    out property <length> control-height: 56px;
    out property <length> button-border-radius: 4px;
    out property <length> card-action-button-width: 112px;
    out property <length> action-button-preferred-width: 180px;
    out property <length> page-action-button-width: 270px;
    out property <length> radio-button-preferred-width: 150px;
    out property <length> element-gap: 8px;
    out property <length> section-gap: 12px;
    out property <length> card-border-radius: 8px;
    out property <length> card-padding: 12px;
    out property <length> card-element-spacing: 6px;
    out property <length> narrow-layout-breakpoint: 420px;
    out property <length> medium-layout-breakpoint: 520px;
    out property <length> desktop-layout-breakpoint: 700px;
    out property <length> window-min-height: 520px;
    out property <length> welcome-action-max-width: 4in;
    out property <length> welcome-content-max-width: 8in;
}
